# Generated by Django 4.0.4 on 2022-05-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
